
<?php

// return array(
//     [
//         'key' => 'Ascension Island' ,
//         'title' => 'Ascension Island' ,
//     ],
//     [
//         'key' => 'Andorra' ,
//         'title' => 'Andorra' ,
//     ],
//     [
//         'key' => 'Afghanistan' ,
//         'title' => 'Afghanistan' ,
//     ],
//     [
//         'key' => 'Antigua And Barbuda' ,
//         'title' => 'Antigua And Barbuda' ,
//     ],
//     [
//         'key' => 'Anguilla' ,
//         'title' => 'Anguilla' ,
//     ],
// );

// return array(
//         'Ascension Island',
//         'Andorra',
//         'Afghanistan',
//         'Antigua And Barbuda',
//         'Anguilla',
//         'Albania',
// );

// return array(
//    'Ascension Island'  => 'Ascension Island',
//     'Andorra' => 'Andorra',
//     'Afghanistan' => 'Afghanistan',
//     'Antigua And Barbuda' => 'Antigua And Barbuda',
//     'Anguilla' => 'Anguilla',
//     'Albania' => 'Albania',
//     'Armenia' => 'Armenia',
//     'Netherlands Antilles' => 'Netherlands Antilles',
//     'Angola' => 'Angola',
// );

// return array(
//     '1'=>"Afghanistan",
//     '2'=>"Albania",
//     '3'=>"Algeria",
//     '4'=>"Andorra",
//     '5'=>"Angola",
// );

$countries = array( array("title"=>"Andorra", "id"=>"AD"),
array("title"=>"Afghanistan", "id"=>"AF"),
array("title"=>"Antigua and Barbuda", "id"=>"AG"),
array("title"=>"Anguilla", "id"=>"AI"),
array("title"=>"Albania", "id"=>"AL"),
array("title"=>"Armenia", "id"=>"AM"),
array("title"=>"Netherlands Antilles", "id"=>"AN"),
array("title"=>"Angola", "id"=>"AO"),
array("title"=>"Asia/Pacific Region", "id"=>"AP"),
array("title"=>"Antarctica", "id"=>"AQ"),
array("title"=>"Argentina", "id"=>"AR"),
array("title"=>"American Samoa", "id"=>"AS"),
array("title"=>"Austria", "id"=>"AT"),
array("title"=>"Australia", "id"=>"AU"),
array("title"=>"Aruba", "id"=>"AW"),
array("title"=>"Aland Islands", "id"=>"AX"),
array("title"=>"Azerbaijan", "id"=>"AZ"),
array("title"=>"Bosnia and Herzegovina", "id"=>"BA"),
array("title"=>"Barbados", "id"=>"BB"),
array("title"=>"Bangladesh", "id"=>"BD"),
array("title"=>"Belgium", "id"=>"BE"),
array("title"=>"Burkina Faso", "id"=>"BF"),
array("title"=>"Bulgaria", "id"=>"BG"),
array("title"=>"Bahrain", "id"=>"BH"),
array("title"=>"Burundi", "id"=>"BI"),
array("title"=>"Benin", "id"=>"BJ"),
array("title"=>"Bermuda", "id"=>"BM"),
array("title"=>"Brunei Darussalam", "id"=>"BN"),
array("title"=>"Bolivia", "id"=>"BO"),
array("title"=>"Brazil", "id"=>"BR"),
array("title"=>"Bahamas", "id"=>"BS"),
array("title"=>"Bhutan", "id"=>"BT"),
array("title"=>"Bouvet Island", "id"=>"BV"),
array("title"=>"Botswana", "id"=>"BW"),
array("title"=>"Belarus", "id"=>"BY"),
array("title"=>"Belize", "id"=>"BZ"),
array("title"=>"Canada", "id"=>"CA"),
array("title"=>"Cocos (Keeling) Islands", "id"=>"CC"),
array("title"=>"Congo", "id"=>"CD"),
array("title"=>"Central African Republic", "id"=>"CF"),
array("title"=>"Congo", "id"=>"CG"),
array("title"=>"Switzerland", "id"=>"CH"),
array("title"=>"Cote d'Ivoire", "id"=>"CI"),
array("title"=>"Cook Islands", "id"=>"CK"),
array("title"=>"Chile", "id"=>"CL"),
array("title"=>"Cameroon", "id"=>"CM"),
array("title"=>"China", "id"=>"CN"),
array("title"=>"Colombia", "id"=>"CO"),
array("title"=>"Costa Rica", "id"=>"CR"),
array("title"=>"Cuba", "id"=>"CU"),
array("title"=>"Cape Verde", "id"=>"CV"),
array("title"=>"Christmas Island", "id"=>"CX"),
array("title"=>"Cyprus", "id"=>"CY"),
array("title"=>"Czech Republic", "id"=>"CZ"),
array("title"=>"Germany", "id"=>"DE"),
array("title"=>"Djibouti", "id"=>"DJ"),
array("title"=>"Denmark", "id"=>"DK"),
array("title"=>"Dominica", "id"=>"DM"),
array("title"=>"Dominican Republic", "id"=>"DO"),
array("title"=>"Algeria", "id"=>"DZ"),
array("title"=>"Ecuador", "id"=>"EC"),
array("title"=>"Estonia", "id"=>"EE"),
array("title"=>"Egypt", "id"=>"EG"),
array("title"=>"Western Sahara", "id"=>"EH"),
array("title"=>"Eritrea", "id"=>"ER"),
array("title"=>"Spain", "id"=>"ES"),
array("title"=>"Ethiopia", "id"=>"ET"),
array("title"=>"Europe", "id"=>"EU"),
array("title"=>"Finland", "id"=>"FI"),
array("title"=>"Fiji", "id"=>"FJ"),
array("title"=>"Falkland Islands (Malvinas)", "id"=>"FK"),
array("title"=>"Micronesia", "id"=>"FM"),
array("title"=>"Faroe Islands", "id"=>"FO"),
array("title"=>"France", "id"=>"FR"),
array("title"=>"Gabon", "id"=>"GA"),
array("title"=>"United Kingdom", "id"=>"GB"),
array("title"=>"Grenada", "id"=>"GD"),
array("title"=>"Georgia", "id"=>"GE"),
array("title"=>"French Guiana", "id"=>"GF"),
array("title"=>"Guernsey", "id"=>"GG"),
array("title"=>"Ghana", "id"=>"GH"),
array("title"=>"Gibraltar", "id"=>"GI"),
array("title"=>"Greenland", "id"=>"GL"),
array("title"=>"Gambia", "id"=>"GM"),
array("title"=>"Guinea", "id"=>"GN"),
array("title"=>"Guadeloupe", "id"=>"GP"),
array("title"=>"Equatorial Guinea", "id"=>"GQ"),
array("title"=>"Greece", "id"=>"GR"),
array("title"=>"South Georgia and the South Sandwich Islands", "id"=>"GS"),
array("title"=>"Guatemala", "id"=>"GT"),
array("title"=>"Guam", "id"=>"GU"),
array("title"=>"Guinea-Bissau", "id"=>"GW"),
array("title"=>"Guyana", "id"=>"GY"),
array("title"=>"Hong Kong", "id"=>"HK"),
array("title"=>"Heard Island and McDonald Islands", "id"=>"HM"),
array("title"=>"Honduras", "id"=>"HN"),
array("title"=>"Croatia", "id"=>"HR"),
array("title"=>"Haiti", "id"=>"HT"),
array("title"=>"Hungary", "id"=>"HU"),
array("title"=>"Indonesia", "id"=>"ID"),
array("title"=>"Ireland", "id"=>"IE"),
array("title"=>"Isle of Man", "id"=>"IM"),
array("title"=>"India", "id"=>"IN"),
array("title"=>"British Indian Ocean Territory", "id"=>"IO"),
array("title"=>"Iraq", "id"=>"IQ"),
array("title"=>"Iran", "id"=>"IR"),
array("title"=>"Iceland", "id"=>"IS"),
array("title"=>"Italy", "id"=>"IT"),
array("title"=>"Jersey", "id"=>"JE"),
array("title"=>"Jamaica", "id"=>"JM"),
array("title"=>"Jordan", "id"=>"JO"),
array("title"=>"Japan", "id"=>"JP"),
array("title"=>"Kenya", "id"=>"KE"),
array("title"=>"Kyrgyzstan", "id"=>"KG"),
array("title"=>"Cambodia", "id"=>"KH"),
array("title"=>"Kiribati", "id"=>"KI"),
array("title"=>"Comoros", "id"=>"KM"),
array("title"=>"Saint Kitts and Nevis", "id"=>"KN"),
array("title"=>"Korea", "id"=>"KP"),
array("title"=>"Korea", "id"=>"KR"),
array("title"=>"Kuwait", "id"=>"KW"),
array("title"=>"Cayman Islands", "id"=>"KY"),
array("title"=>"Kazakhstan", "id"=>"KZ"),
array("title"=>"Lao People's Democratic Republic", "id"=>"LA"),
array("title"=>"Lebanon", "id"=>"LB"),
array("title"=>"Saint Lucia", "id"=>"LC"),
array("title"=>"Liechtenstein", "id"=>"LI"),
array("title"=>"Sri Lanka", "id"=>"LK"),
array("title"=>"Liberia", "id"=>"LR"),
array("title"=>"Lesotho", "id"=>"LS"),
array("title"=>"Lithuania", "id"=>"LT"),
array("title"=>"Luxembourg", "id"=>"LU"),
array("title"=>"Latvia", "id"=>"LV"),
array("title"=>"Libyan Arab Jamahiriya", "id"=>"LY"),
array("title"=>"Morocco", "id"=>"MA"),
array("title"=>"Monaco", "id"=>"MC"),
array("title"=>"Moldova", "id"=>"MD"),
array("title"=>"Montenegro", "id"=>"ME"),
array("title"=>"Madagascar", "id"=>"MG"),
array("title"=>"Marshall Islands", "id"=>"MH"),
array("title"=>"Macedonia", "id"=>"MK"),
array("title"=>"Mali", "id"=>"ML"),
array("title"=>"Myanmar", "id"=>"MM"),
array("title"=>"Mongolia", "id"=>"MN"),
array("title"=>"Macao", "id"=>"MO"),
array("title"=>"Northern Mariana Islands", "id"=>"MP"),
array("title"=>"Martinique", "id"=>"MQ"),
array("title"=>"Mauritania", "id"=>"MR"),
array("title"=>"Montserrat", "id"=>"MS"),
array("title"=>"Malta", "id"=>"MT"),
array("title"=>"Mauritius", "id"=>"MU"),
array("title"=>"Maldives", "id"=>"MV"),
array("title"=>"Malawi", "id"=>"MW"),
array("title"=>"Mexico", "id"=>"MX"),
array("title"=>"Malaysia", "id"=>"MY"),
array("title"=>"Mozambique", "id"=>"MZ"),
array("title"=>"Namibia", "id"=>"NA"),
array("title"=>"New Caledonia", "id"=>"NC"),
array("title"=>"Niger", "id"=>"NE"),
array("title"=>"Norfolk Island", "id"=>"NF"),
array("title"=>"Nigeria", "id"=>"NG"),
array("title"=>"Nicaragua", "id"=>"NI"),
array("title"=>"Netherlands", "id"=>"NL"),
array("title"=>"Norway", "id"=>"NO"),
array("title"=>"Nepal", "id"=>"NP"),
array("title"=>"Nauru", "id"=>"NR"),
array("title"=>"Niue", "id"=>"NU"),
array("title"=>"New Zealand", "id"=>"NZ"),
array("title"=>"Oman", "id"=>"OM"),
array("title"=>"Panama", "id"=>"PA"),
array("title"=>"Peru", "id"=>"PE"),
array("title"=>"French Polynesia", "id"=>"PF"),
array("title"=>"Papua New Guinea", "id"=>"PG"),
array("title"=>"Philippines", "id"=>"PH"),
array("title"=>"Pakistan", "id"=>"PK"),
array("title"=>"Poland", "id"=>"PL"),
array("title"=>"Saint Pierre and Miquelon", "id"=>"PM"),
array("title"=>"Pitcairn", "id"=>"PN"),
array("title"=>"Puerto Rico", "id"=>"PR"),
array("title"=>"Palestinian Territory", "id"=>"PS"),
array("title"=>"Portugal", "id"=>"PT"),
array("title"=>"Palau", "id"=>"PW"),
array("title"=>"Paraguay", "id"=>"PY"),
array("title"=>"Qatar", "id"=>"QA"),
array("title"=>"Reunion", "id"=>"RE"),
array("title"=>"Romania", "id"=>"RO"),
array("title"=>"Serbia", "id"=>"RS"),
array("title"=>"Russian Federation", "id"=>"RU"),
array("title"=>"Rwanda", "id"=>"RW"),
array("title"=>"Saudi Arabia", "id"=>"SA"),
array("title"=>"Solomon Islands", "id"=>"SB"),
array("title"=>"Seychelles", "id"=>"SC"),
array("title"=>"Sudan", "id"=>"SD"),
array("title"=>"Sweden", "id"=>"SE"),
array("title"=>"Singapore", "id"=>"SG"),
array("title"=>"Saint Helena", "id"=>"SH"),
array("title"=>"Slovenia", "id"=>"SI"),
array("title"=>"Svalbard and Jan Mayen", "id"=>"SJ"),
array("title"=>"Slovakia", "id"=>"SK"),
array("title"=>"Sierra Leone", "id"=>"SL"),
array("title"=>"San Marino", "id"=>"SM"),
array("title"=>"Senegal", "id"=>"SN"),
array("title"=>"Somalia", "id"=>"SO"),
array("title"=>"Surititle", "id"=>"SR"),
array("title"=>"Sao Tome and Principe", "id"=>"ST"),
array("title"=>"El Salvador", "id"=>"SV"),
array("title"=>"Syrian Arab Republic", "id"=>"SY"),
array("title"=>"Swaziland", "id"=>"SZ"),
array("title"=>"Turks and Caicos Islands", "id"=>"TC"),
array("title"=>"Chad", "id"=>"TD"),
array("title"=>"French Southern Territories", "id"=>"TF"),
array("title"=>"Togo", "id"=>"TG"),
array("title"=>"Thailand", "id"=>"TH"),
array("title"=>"Tajikistan", "id"=>"TJ"),
array("title"=>"Tokelau", "id"=>"TK"),
array("title"=>"Timor-Leste", "id"=>"TL"),
array("title"=>"Turkmenistan", "id"=>"TM"),
array("title"=>"Tunisia", "id"=>"TN"),
array("title"=>"Tonga", "id"=>"TO"),
array("title"=>"Turkey", "id"=>"TR"),
array("title"=>"Trinidad and Tobago", "id"=>"TT"),
array("title"=>"Tuvalu", "id"=>"TV"),
array("title"=>"Taiwan", "id"=>"TW"),
array("title"=>"Tanzania", "id"=>"TZ"),
array("title"=>"Ukraine", "id"=>"UA"),
array("title"=>"Uganda", "id"=>"UG"),
array("title"=>"United Arab Emirates", "id"=>"AE"),
array("title"=>"United States Minor Outlying Islands", "id"=>"UM"),
array("title"=>"United States", "id"=>"US"),
array("title"=>"Uruguay", "id"=>"UY"),
array("title"=>"Uzbekistan", "id"=>"UZ"),
array("title"=>"Holy See (Vatican City State)", "id"=>"VA"),
array("title"=>"Saint Vincent and the Grenadines", "id"=>"VC"),
array("title"=>"Venezuela", "id"=>"VE"),
array("title"=>"Virgin Islands", "id"=>"VG"),
array("title"=>"Virgin Islands", "id"=>"VI"),
array("title"=>"Vietnam", "id"=>"VN"),
array("title"=>"Vanuatu", "id"=>"VU"),
array("title"=>"Wallis and Futuna", "id"=>"WF"),
array("title"=>"Samoa", "id"=>"WS"),
array("title"=>"Yemen", "id"=>"YE"),
array("title"=>"Mayotte", "id"=>"YT"),
array("title"=>"South Africa", "id"=>"ZA"),
array("title"=>"Zambia", "id"=>"ZM"),
array("title"=>"Zimbabwe", "id"=>"ZW")
);
return $countries;


// return array(
//     "Afghanistan", "Albania", "Algeria", "Andorra", "Angola", "Antigua and Barbuda", "Argentina", "Armenia",
//     "Australia", "Austria", "Azerbaijan", "Bahamas", "Bahrain", "Bangladesh", "Barbados", "Belarus", "Belgium",
//     "Belize", "Benin", "Bhutan", "Bolivia", "Bosnia and Herzegovina", "Botswana", "Brazil", "Brunei", "Bulgaria",
//     "Burkina Faso", "Burundi", "Cambodia", "Cameroon", "Canada", "Cape Verde", "Central African Republic", "Chad",
//     "Chile", "China", "Colombi", "Comoros", "Congo (Brazzaville)", "Congo", "Costa Rica", "Cote d'Ivoire", "Croatia",
//     "Cuba", "Cyprus", "Czech Republic", "Denmark", "Djibouti", "Dominica", "Dominican Republic", "East Timor (Timor Timur)",
//     "Ecuador", "Egypt", "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia", "Ethiopia", "Fiji", "Finland", "France",
//     "Gabon", "Gambia, The", "Georgia", "Germany", "Ghana", "Greece", "Grenada", "Guatemala", "Guinea", "Guinea-Bissau",
//     "Guyana", "Haiti", "Honduras", "Hungary", "Iceland", "India", "Indonesia", "Iran", "Iraq", "Ireland", "Israel",
//     "Italy", "Jamaica", "Japan", "Jordan", "Kazakhstan", "Kenya", "Kiribati", "Korea, North", "Korea, South", "Kuwait",
//     "Kyrgyzstan", "Laos", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya", "Liechtenstein", "Lithuania", "Luxembourg",
//     "Macedonia", "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali", "Malta", "Marshall Islands", "Mauritania",
//     "Mauritius", "Mexico", "Micronesia", "Moldova", "Monaco", "Mongolia", "Morocco", "Mozambique", "Myanmar", "Namibia",
//     "Nauru", "Nepa", "Netherlands", "New Zealand", "Nicaragua", "Niger", "Nigeria", "Norway", "Oman", "Pakistan", "Palau",
//     "Panama", "Papua New Guinea", "Paraguay", "Peru", "Philippines", "Poland", "Portugal", "Qatar", "Romania", "Russia",
//     "Rwanda", "Saint Kitts and Nevis", "Saint Lucia", "Saint Vincent", "Samoa", "San Marino", "Sao Tome and Principe",
//     "Saudi Arabia", "Senegal", "Serbia and Montenegro", "Seychelles", "Sierra Leone", "Singapore", "Slovakia", "Slovenia",
//     "Solomon Islands", "Somalia", "South Africa", "Spain", "Sri Lanka", "Sudan", "Surititle", "Swaziland", "Sweden",
//     "Switzerland", "Syria", "Taiwan", "Tajikistan", "Tanzania", "Thailand", "Togo", "Tonga", "Trinidad and Tobago",
//     "Tunisia", "Turkey", "Turkmenistan", "Tuvalu", "Uganda", "Ukraine", "United Arab Emirates", "United Kingdom",
//     "United States", "Uruguay", "Uzbekistan", "Vanuatu", "Vatican City", "Venezuela", "Vietnam", "Yemen", "Zambia", "Zimbabwe"
//     );

// return array(
//     '1'=>"Afghanistan",
//     '2'=>"Albania",
//     '3'=>"Algeria",
//     '4'=>"Andorra",
//     '5'=>"Angola",
//     '6'=>"Antigua and Barbuda",
//     '7'=>"Argentina",
//     '8'=>"Armenia",
//     '9'=>"Australia",
//     '10'=>"Austria",
//     '11'=>"Azerbaijan",
//     '12'=>"Bahamas",
//     '13'=>"Bahrain",
//     '14'=>"Bangladesh",
//     '15'=>"Barbados",
//     '16'=>"Belarus",
//     '17'=>"Belgium",
//     '18'=>"Belize",
//     '19'=>"Benin",
//     '20'=>"Bhutan",
//     '21'=>"Bolivia",
//     '22'=>"Bosnia and Herzegovina",
//     '23'=>"Botswana",
//     '24'=>"Brazil",
//     '25'=>"Brunei",
//     '26'=>"Bulgaria",
//     '27'=>"Burkina Faso",
//     '28'=>"Burundi",
//     '29'=>"Cambodia",
//     '30'=>"Cameroon",
//     '31'=>"Canada",
//     '32'=>"Cape Verde",
//     '33'=>"Central African Republic",
//     '34'=>"Chad",
//     '35'=>"Chile",
//     '36'=>"China",
//     '37'=>"Colombi",
//     '38'=>"Comoros",
//     '39'=>"Congo (Brazzaville)",
//     '40'=>"Congo",
//     '41'=>"Costa Rica",
//     '42'=>"Cote d'Ivoire",
//     '43'=>"Croatia",
//     '44'=>"Cuba",
//     '45'=>"Cyprus",
//     '46'=>"Czech Republic",
//     '47'=>"Denmark",
//     '48'=>"Djibouti",
//     '49'=>"Dominica",
//     '50'=>"Dominican Republic",
//     '51'=>"East Timor (Timor Timur)",
//     '52'=>"Ecuador",
//     '53'=>"Egypt",
//     '54'=>"El Salvador",
//     '55'=>"Equatorial Guinea",
//     '56'=>"Eritrea",
//     '57'=>"Estonia",
//     '58'=>"Ethiopia",
//     '59'=>"Fiji",
//     '60'=>"Finland",
//     '61'=>"France",
//     '62'=>"Gabon",
//     '63'=>"Gambia, The",
//     '64'=>"Georgia",
//     '65'=>"Germany",
//     '66'=>"Ghana",
//     '67'=>"Greece",
//     '68'=>"Grenada",
//     '69'=>"Guatemala",
//     '70'=>"Guinea",
//     '71'=>"Guinea-Bissau",
//     '72'=>"Guyana",
//     '73'=>"Haiti",
//     '74'=>"Honduras",
//     '75'=>"Hungary",
//     '76'=>"Iceland",
//     '77'=>"India",
//     '78'=>"Indonesia",
//     '79'=>"Iran",
//     '80'=>"Iraq",
//     '81'=>"Ireland",
//     '82'=>"Israel",
//     '83'=>"Italy",
//     '84'=>"Jamaica",
//     '85'=>"Japan",
//     '86'=>"Jordan",
//     '87'=>"Kazakhstan",
//     '88'=>"Kenya",
//     '89'=>"Kiribati",
//     '90'=>"Korea, North",
//     '91'=>"Korea, South",
//     '92'=>"Kuwait",
//     '93'=>"Kyrgyzstan",
//     '94'=>"Laos",
//     '95'=>"Latvia",
//     '96'=>"Lebanon",
//     '97'=>"Lesotho",
//     '98'=>"Liberia",
//     '99'=>"Libya",
//     '100'=>"Liechtenstein",
//     '101'=>"Lithuania",
//     '102'=>"Luxembourg",
//     '103'=>"Macedonia",
//     '104'=>"Madagascar",
//     '105'=>"Malawi",
//     '106'=>"Malaysia",
//     '107'=>"Maldives",
//     '108'=>"Mali",
//     '109'=>"Malta",
//     '110'=>"Marshall Islands",
//     '111'=>"Mauritania",
//     '112'=>"Mauritius",
//     '113'=>"Mexico",
//     '114'=>"Micronesia",
//     '115'=>"Moldova",
//     '116'=>"Monaco",
//     '117'=>"Mongolia",
//     '118'=>"Morocco",
//     '119'=>"Mozambique",
//     '120'=>"Myanmar",
//     '121'=>"Namibia",
//     '122'=>"Nauru",
//     '123'=>"Nepa",
//     '124'=>"Netherlands",
//     '125'=>"New Zealand",
//     '126'=>"Nicaragua",
//     '127'=>"Niger",
//     '128'=>"Nigeria",
//     '129'=>"Norway",
//     '130'=>"Oman",
//     '131'=>"Pakistan",
//     '132'=>"Palau",
//     '133'=>"Panama",
//     '134'=>"Papua New Guinea",
//     '135'=>"Paraguay",
//     '136'=>"Peru",
//     '137'=>"Philippines",
//     '138'=>"Poland",
//     '139'=>"Portugal",
//     '140'=>"Qatar",
//     '141'=>"Romania",
//     '142'=>"Russia",
//     '143'=>"Rwanda",
//     '144'=>"Saint Kitts and Nevis",
//     '145'=>"Saint Lucia",
//     '146'=>"Saint Vincent",
//     '147'=>"Samoa",
//     '148'=>"San Marino",
//     '149'=>"Sao Tome and Principe",
//     '150'=>"Saudi Arabia",
//     '151'=>"Senegal",
//     '152'=>"Serbia and Montenegro",
//     '153'=>"Seychelles",
//     '154'=>"Sierra Leone",
//     '155'=>"Singapore",
//     '156'=>"Slovakia",
//     '157'=>"Slovenia",
//     '158'=>"Solomon Islands",
//     '159'=>"Somalia",
//     '160'=>"South Africa",
//     '161'=>"Spain",
//     '162'=>"Sri Lanka",
//     '163'=>"Sudan",
//     '164'=>"Surititle",
//     '165'=>"Swaziland",
//     '166'=>"Sweden",
//     '167'=>"Switzerland",
//     '168'=>"Syria",
//     '169'=>"Taiwan",
//     '170'=>"Tajikistan",
//     '171'=>"Tanzania",
//     '172'=>"Thailand",
//     '173'=>"Togo",
//     '174'=>"Tonga",
//     '175'=>"Trinidad and Tobago",
//     '176'=>"Tunisia",
//     '177'=>"Turkey",
//     '178'=>"Turkmenistan",
//     '179'=>"Tuvalu",
//     '180'=>"Uganda",
//     '181'=>"Ukraine",
//     '182'=>"United Arab Emirates",
//     '183'=>"United Kingdom",
//     '184'=>"United States",
//     '185'=>"Uruguay",
//     '186'=>"Uzbekistan",
//     '187'=>"Vanuatu",
//     '188'=>"Vatican City",
//     '189'=>"Venezuela",
//     '190'=>"Vietnam",
//     '191'=>"Yemen",
//     '192'=>"Zambia",
//     '193'=>"Zimbabwe"
//     );

// return array(
//     "Afghanistan",
//     "Albania",
//     "Algeria",
//     "Andorra",
//     "Angola",
//     "Antigua and Barbuda",
//     "Argentina",
//     "Armenia",
//     "Australia",
//     "Austria",
//     "Azerbaijan",
//     "Bahamas",
//     "Bahrain",
//     "Bangladesh",
//     "Barbados",
//     "Belarus",
//     "Belgium",
//     "Belize",
//     "Benin",
//     "Bhutan",
//     "Bolivia",
//     "Bosnia and Herzegovina",
//     "Botswana",
//     "Brazil",
//     "Brunei",
//     "Bulgaria",
//     "Burkina Faso",
//     "Burundi",
//     "Cambodia",
//     "Cameroon",
//     "Canada",
//     "Cape Verde",
//     "Central African Republic",
//     "Chad",
//     "Chile",
//     "China",
//     "Colombi",
//     "Comoros",
//     "Congo (Brazzaville)",
//     "Congo",
//     "Costa Rica",
//     "Cote d'Ivoire",
//     "Croatia",
//     "Cuba",
//     "Cyprus",
//     "Czech Republic",
//     "Denmark",
//     "Djibouti",
//     "Dominica",
//     "Dominican Republic",
//     "East Timor (Timor Timur)",
//     "Ecuador",
//     "Egypt",
//     "El Salvador",
//     "Equatorial Guinea",
//     "Eritrea",
//     "Estonia",
//     "Ethiopia",
//     "Fiji",
//     "Finland",
//     "France",
//     "Gabon",
//     "Gambia, The",
//     "Georgia",
//     "Germany",
//     "Ghana",
//     "Greece",
//     "Grenada",
//     "Guatemala",
//     "Guinea",
//     "Guinea-Bissau",
//     "Guyana",
//     "Haiti",
//     "Honduras",
//     "Hungary",
//     "Iceland",
//     "India",
//     "Indonesia",
//     "Iran",
//     "Iraq",
//     "Ireland",
//     "Italy",
//     "Jamaica",
//     "Japan",
//     "Jordan",
//     "Kazakhstan",
//     "Kenya",
//     "Kiribati",
//     "Korea, North",
//     "Korea, South",
//     "Kuwait",
//     "Kyrgyzstan",
//     "Laos",
//     "Latvia",
//     "Lebanon",
//     "Lesotho",
//     "Liberia",
//     "Libya",
//     "Liechtenstein",
//     "Lithuania",
//     "Luxembourg",
//     "Macedonia",
//     "Madagascar",
//     "Malawi",
//     "Malaysia",
//     "Maldives",
//     "Mali",
//     "Malta",
//     "Marshall Islands",
//     "Mauritania",
//     "Mauritius",
//     "Mexico",
//     "Micronesia",
//     "Moldova",
//     "Monaco",
//     "Mongolia",
//     "Morocco",
//     "Mozambique",
//     "Myanmar",
//     "Namibia",
//     "Nauru",
//     "Nepal",
//     "Netherlands",
//     "New Zealand",
//     "Nicaragua",
//     "Niger",
//     "Nigeria",
//     "Norway",
//     "Oman",
//     "Pakistan",
//     "Palau",
//     "Panama",
//     "Papua New Guinea",
//     "Paraguay",
//     "Peru",
//     "Philippines",
//     "Poland",
//     "Portugal",
//     "Qatar",
//     "Romania",
//     "Russia",
//     "Rwanda",
//     "Saint Kitts and Nevis",
//     "Saint Lucia",
//     "Saint Vincent",
//     "Samoa",
//     "San Marino",
//     "Sao Tome and Principe",
//     "Saudi Arabia",
//     "Senegal",
//     "Serbia and Montenegro",
//     "Seychelles",
//     "Sierra Leone",
//     "Singapore",
//     "Slovakia",
//     "Slovenia",
//     "Solomon Islands",
//     "Somalia",
//     "South Africa",
//     "Spain",
//     "Sri Lanka",
//     "Sudan",
//     "Surititle",
//     "Swaziland",
//     "Sweden",
//     "Switzerland",
//     "Syria",
//     "Taiwan",
//     "Tajikistan",
//     "Tanzania",
//     "Thailand",
//     "Togo",
//     "Tonga",
//     "Trinidad and Tobago",
//     "Tunisia",
//     "Turkey",
//     "Turkmenistan",
//     "Tuvalu",
//     "Uganda",
//     "Ukraine",
//     "United Arab Emirates",
//     "United Kingdom",
//     "United States",
//     "Uruguay",
//     "Uzbekistan",
//     "Vanuatu",
//     "Vatican City",
//     "Venezuela",
//     "Vietnam",
//     "Yemen",
//     "Zambia",
//     "Zimbabwe"
// );
// return 
// [
//    'Ascension Island'  => 'Ascension Island',
//     'Andorra' => 'Andorra',
//     'Afghanistan' => 'Afghanistan',
//     'Antigua And Barbuda' => 'Antigua And Barbuda',
//     'Anguilla' => 'Anguilla',
//     'Albania' => 'Albania',
//     'Armenia' => 'Armenia',
//     'Netherlands Antilles' => 'Netherlands Antilles',
//     'Angola' => 'Angola',
//     'Antarctica' => 'Antarctica',
//     'Argentina' => 'Argentina',
//     'American Samoa' => 'American Samoa',
//     'Austria' => 'Austria',
//     'Australia' => 'Australia',
//     'Aruba' => 'Aruba',
//     'Ãƒâ€¦land' => 'Ãƒâ€¦land',
//     'Azerbaijan' => 'Azerbaijan',
//     'Bosnia And Herzegovina' => 'Bosnia And Herzegovina',
//     'Barbados' => 'Barbados',
//     'Belgium' => 'Belgium',
//     'Bangladesh' => 'Bangladesh',
//     'Burkina Faso' => 'Burkina Faso',
//     'Bulgaria' => 'Bulgaria',
//     'Bahrain' => 'Bahrain',
//     'Burundi' => 'Burundi',
//     'Benin' => 'Benin',
//     'Bermuda' => 'Bermuda',
//     'Brunei Darussalam' => 'Brunei Darussalam',
//     'Bolivia' => 'Bolivia',
//     'Brazil' => 'Brazil',
//     'Bahamas' => 'Bahamas',
//     'Bhutan' => 'Bhutan',
//     'Bouvet Island' => 'Bouvet Island',
//     'Botswana' => 'Botswana',
//     'Belarus' => 'Belarus',
//     'Belize' => 'Belize',
//     'Canada' => 'Canada',
//     'Cocos (Keeling) Islands' => 'Cocos (Keeling) Islands',
//     'Congo (Democratic Republic)' => 'Congo (Democratic Republic)',
//     'Central African Republic' => 'Central African Republic',
//     'Congo (Republic)' => 'Congo (Republic)',
//     'Switzerland' => 'Switzerland',
//     'Cote D\'Ivoire' => 'Cote D\'Ivoire',
//     'Cook Islands' => 'Cook Islands',
//     'Chile' => 'Chile',
//     'Cameroon' => 'Cameroon',
//     'PeopleÃ¢â‚¬â„¢s Republic of China' => 'PeopleÃ¢â‚¬â„¢s Republic of China',
//     'Colombia' => 'Colombia',
//     'Costa Rica' => 'Costa Rica',
//     'Cuba' => 'Cuba',
//     'Cape Verde' => 'Cape Verde',
//     'Christmas Island' => 'Christmas Island',
//     'Cyprus' => 'Cyprus',
//     'Czech Republic' => 'Czech Republic',
//     'Germany' => 'Germany',
//     'Djibouti' => 'Djibouti',
//     'Denmark' => 'Denmark',
//     'Dominica' => 'Dominica',
//     'Dominican Republic' => 'Dominican Republic',
//     'Algeria' => 'Algeria',
//     'Ecuador' => 'Ecuador',
//     'Estonia' => 'Estonia',
//     'Egypt' => 'Egypt',
//     'Eritrea' => 'Eritrea',
//     'Spain' => 'Spain',
//     'Ethiopia' => 'Ethiopia',
//     'European Union' => 'European Union',
//     'Finland' => 'Finland',
//     'Fiji' => 'Fiji',
//     'Falkland Islands (Malvinas)' => 'Falkland Islands (Malvinas)',
//     'Micronesia, Federated States Of' => 'Micronesia, Federated States Of',
//     'Faroe Islands' => 'Faroe Islands',
//     'France' => 'France',
//     'Gabon' => 'Gabon',
//     'United Arab Emirates' => 'United Arab Emirates',
//     'United Kingdom' => 'United Kingdom',
//     'Grenada' => 'Grenada',
//     'Georgia' => 'Georgia',
//     'French Guiana' => 'French Guiana',
//     'Guernsey' => 'Guernsey',
//     'Ghana' => 'Ghana',
//     'Gibraltar' => 'Gibraltar',
//     'Greenland' => 'Greenland',
//     'Gambia' => 'Gambia',
//     'Guinea' => 'Guinea',
//     'Guadeloupe' => 'Guadeloupe',
//     'Equatorial Guinea' => 'Equatorial Guinea',
//     'Greece' => 'Greece',
//     'South Georgia And The South Sandwich Islands' => 'South Georgia And The South Sandwich Islands',
//     'Guatemala' => 'Guatemala',
//     'Guam' => 'Guam',
// 'Guinea-Bissau' => 'Guinea-Bissau',
// 'Guyana' => 'Guyana',
// 'Hong Kong' => 'Hong Kong',
// 'Heard And Mc Donald Islands' => 'Heard And Mc Donald Islands',
// 'Honduras' => 'Honduras',
// 'Croatia (local title: Hrvatska)' => 'Croatia (local title: Hrvatska)',
// 'Haiti' => 'Haiti',
// 'Hungary' => 'Hungary',
// 'Indonesia' => 'Indonesia',
// 'Ireland' => 'Ireland',
// 'Isle of Man' => 'Isle of Man',
// 'India' => 'India',
// 'British Indian Ocean Territory' => 'British Indian Ocean Territory',
// 'Iraq' => 'Iraq',
// 'Iran (Islamic Republic Of)' => 'Iran (Islamic Republic Of)',
// 'Iceland' => 'Iceland',
// 'Italy' => 'Italy',
// 'Jersey' => 'Jersey',
// 'Jamaica' => 'Jamaica',
// 'Jordan' => 'Jordan',
// 'Japan' => 'Japan',
// 'Kenya' => 'Kenya',
// 'Kyrgyzstan' => 'Kyrgyzstan',
// 'Cambodia' => 'Cambodia',
// 'Kiribati' => 'Kiribati',
// 'Comoros' => 'Comoros',
// 'Saint Kitts And Nevis' => 'Saint Kitts And Nevis',
// 'Korea, Republic Of' => 'Korea, Republic Of',
// 'Kuwait' => 'Kuwait',
// 'Cayman Islands' => 'Cayman Islands',
// 'Kazakhstan' => 'Kazakhstan',
// 'Lao PeopleÃ¢â‚¬â„¢s Democratic Republic' => 'Lao PeopleÃ¢â‚¬â„¢s Democratic Republic',
// 'Lebanon' => 'Lebanon',
// 'Saint Lucia' => 'Saint Lucia',
// 'Liechtenstein' => 'Liechtenstein',
// 'Sri Lanka' => 'Sri Lanka',
// 'Liberia' => 'Liberia',
// 'Lesotho' => 'Lesotho',
// 'Lithuania' => 'Lithuania',
// 'Luxembourg' => 'Luxembourg',
// 'Latvia' => 'Latvia',
// 'Libyan Arab Jamahiriya' => 'Libyan Arab Jamahiriya',
// 'Morocco' => 'Morocco',
// 'Monaco' => 'Monaco',
// 'Moldova, Republic Of' => 'Moldova, Republic Of',
// 'Montenegro' => 'Montenegro',
// 'Madagascar' => 'Madagascar',
// 'Marshall Islands' => 'Marshall Islands',
// 'Macedonia, The Former Yugoslav Republic Of' => 'Macedonia, The Former Yugoslav Republic Of',
// 'Mali' => 'Mali',
// 'Myanmar' => 'Myanmar',
// 'Mongolia' => 'Mongolia',
// 'Macau' => 'Macau',
// 'Northern Mariana Islands' => 'Northern Mariana Islands',
// 'Martinique' => 'Martinique',
// 'Mauritania' => 'Mauritania',
// 'Montserrat' => 'Montserrat',
// 'Malta' => 'Malta',
// 'Mauritius' => 'Mauritius',
// 'Maldives' => 'Maldives',
// 'Malawi' => 'Malawi',
// 'Mexico' => 'Mexico',
// 'Malaysia' => 'Malaysia',
// 'Mozambique' => 'Mozambique',
// 'Namibia' => 'Namibia',
// 'New Caledonia' => 'New Caledonia',
// 'Niger' => 'Niger',
// 'Norfolk Island' => 'Norfolk Island',
// 'Nigeria' => 'Nigeria',
// 'Nicaragua' => 'Nicaragua',
// 'Netherlands' => 'Netherlands',
// 'Norway' => 'Norway',
// 'Nepal' => 'Nepal',
// 'Nauru' => 'Nauru',
// 'Niue' => 'Niue',
// 'New Zealand' => 'New Zealand',
// 'Oman' => 'Oman',
// 'Panama' => 'Panama',
// 'Peru' => 'Peru',
// 'French Polynesia' => 'French Polynesia',
// 'Papua New Guinea' => 'Papua New Guinea',
// 'Philippines, Republic of the' => 'Philippines, Republic of the',
// 'Pakistan' => 'Pakistan',
// 'Poland' => 'Poland',
// 'St. Pierre And Miquelon' => 'St. Pierre And Miquelon',
// 'Pitcairn' => 'Pitcairn',
// 'Puerto Rico' => 'Puerto Rico',
// 'Palestine' => 'Palestine',
// 'Portugal' => 'Portugal',
// 'Palau' => 'Palau',
// 'Paraguay' => 'Paraguay',
// 'Qatar' => 'Qatar',
// 'Reunion' => 'Reunion',
// 'Romania' => 'Romania',
// 'Serbia' => 'Serbia',
// 'Russian Federation' => 'Russian Federation',
// 'Rwanda' => 'Rwanda',
// 'Saudi Arabia' => 'Saudi Arabia',
// 'United Kingdom' => 'United Kingdom',
// 'Solomon Islands' => 'Solomon Islands',
// 'Seychelles' => 'Seychelles',
// 'Sudan' => 'Sudan',
// 'Sweden' => 'Sweden',
// 'Singapore' => 'Singapore',
// 'St. Helena' => 'St. Helena',
// 'Slovenia' => 'Slovenia',
// 'Svalbard And Jan Mayen Islands' => 'Svalbard And Jan Mayen Islands',
// 'Slovakia (Slovak Republic)' => 'Slovakia (Slovak Republic)',
// 'Sierra Leone' => 'Sierra Leone',
// 'San Marino' => 'San Marino',
// 'Senegal' => 'Senegal',
// 'Somalia' => 'Somalia',
// 'Surititle' => 'Surititle',
// 'Sao Tome And Principe' => 'Sao Tome And Principe',
// 'Soviet Union' => 'Soviet Union',
// 'El Salvador' => 'El Salvador',
// 'Syrian Arab Republic' => 'Syrian Arab Republic',
// 'Swaziland' => 'Swaziland',
// 'Turks And Caicos Islands' => 'Turks And Caicos Islands',
// 'Chad' => 'Chad',
// 'French Southern Territories' => 'French Southern Territories',
// 'Togo' => 'Togo',
// 'Thailand' => 'Thailand',
// 'Tajikistan' => 'Tajikistan',
// 'Tokelau' => 'Tokelau',
// 'East Timor (new id)' => 'East Timor (new id)',
// 'Turkmenistan' => 'Turkmenistan',
// 'Tunisia' => 'Tunisia',
// 'Tonga' => 'Tonga',
// 'East Timor (old id)' => 'East Timor (old id)',
// 'Turkey' => 'Turkey',
// 'Trinidad And Tobago' => 'Trinidad And Tobago',
// 'Tuvalu' => 'Tuvalu',
// 'Taiwan' => 'Taiwan',
// 'Tanzania, United Republic Of' => 'Tanzania, United Republic Of',
// 'Ukraine' => 'Ukraine',
// 'Uganda' => 'Uganda',
// 'United States Minor Outlying Islands' => 'United States Minor Outlying Islands',
// 'United States' => 'United States',
// 'Uruguay' => 'Uruguay',
// 'Uzbekistan' => 'Uzbekistan',
// 'Vatican City State (Holy See)' => 'Vatican City State (Holy See)',
// 'Saint Vincent And The Grenadines' => 'Saint Vincent And The Grenadines',
// 'Venezuela' => 'Venezuela',
// 'Virgin Islands (British)' => 'Virgin Islands (British)',
// 'Virgin Islands (U.S.)' => 'Virgin Islands (U.S.)',
// 'Viet Nam' => 'Viet Nam',
// 'Vanuatu' => 'Vanuatu',
// 'Wallis And Futuna Islands' => 'Wallis And Futuna Islands',
// 'Samoa' => 'Samoa',
// 'Yemen' => 'Yemen',
// 'Mayotte' => 'Mayotte',
// 'South Africa' => 'South Africa',
// 'Zambia' => 'Zambia',
// 'Zimbabwe' => 'Zimbabwe'
// ];

// return [["AF", "Afghanistan"],  ["AL", "Albania"],  ["DZ", "Algeria"],  ["AS", "American Samoa"],  ["AD", "Andorra"],  ["AO", "Angola"],  ["AI", "Anguilla"],  ["AQ", "Antarctica"],  ["AG", "Antigua and Barbuda"],  ["AR", "Argentina"],  ["AM", "Armenia"],  ["AW", "Aruba"],  ["AU", "Australia"],  ["AT", "Austria"],  ["AZ", "Azerbaijan"],  ["BS", "Bahamas"],  ["BH", "Bahrain"],  ["BD", "Bangladesh"],  ["BB", "Barbados"],  ["BY", "Belarus"],  ["BE", "Belgium"],  ["BZ", "Belize"],  ["BJ", "Benin"],  ["BM", "Bermuda"],  ["BT", "Bhutan"],  ["BO", "Bolivia"],  ["BA", "Bosnia and Herzegovina"],  ["BW", "Botswana"],  ["BV", "Bouvet Island"],  ["BR", "Brazil"],  ["IO", "British Indian Ocean Territory"],  ["BN", "Brunei Darussalam"],  ["BG", "Bulgaria"],  ["BF", "Burkina Faso"],  ["BI", "Burundi"],  ["KH", "Cambodia"],  ["CM", "Cameroon"],  ["CA", "Canada"],  ["CV", "Cape Verde"],  ["KY", "Cayman Islands"],  ["CF", "Central African Republic"],  ["TD", "Chad"],  ["CL", "Chile"],  ["CN", "China"],  ["CX", "Christmas Island"],  ["CC", "Cocos (Keeling) Islands"],  ["CO", "Colombia"],  ["KM", "Comoros"],  ["CG", "Congo"],  ["CD", "Congo, the Democratic Republic of the"],  ["CK", "Cook Islands"],  ["CR", "Costa Rica"],  ["CI", "Cote D'Ivoire"],  ["HR", "Croatia"],  ["CU", "Cuba"],  ["CY", "Cyprus"],  ["CZ", "Czech Republic"],  ["DK", "Denmark"],  ["DJ", "Djibouti"],  ["DM", "Dominica"],  ["DO", "Dominican Republic"],  ["EC", "Ecuador"],  ["EG", "Egypt"],  ["SV", "El Salvador"],  ["GQ", "Equatorial Guinea"],  ["ER", "Eritrea"],  ["EE", "Estonia"],  ["ET", "Ethiopia"],  ["FK", "Falkland Islands (Malvinas)"],  ["FO", "Faroe Islands"],  ["FJ", "Fiji"],  ["FI", "Finland"],  ["FR", "France"],  ["GF", "French Guiana"],  ["PF", "French Polynesia"],  ["TF", "French Southern Territories"],  ["GA", "Gabon"],  ["GM", "Gambia"],  ["GE", "Georgia"],  ["DE", "Germany"],  ["GH", "Ghana"],  ["GI", "Gibraltar"],  ["GR", "Greece"],  ["GL", "Greenland"],  ["GD", "Grenada"],  ["GP", "Guadeloupe"],  ["GU", "Guam"],  ["GT", "Guatemala"],  ["GN", "Guinea"],  ["GW", "Guinea-Bissau"],  ["GY", "Guyana"],  ["HT", "Haiti"],  ["HM", "Heard Island and Mcdonald Islands"],  ["VA", "Holy See (Vatican City State)"],  ["HN", "Honduras"],  ["HK", "Hong Kong"],  ["HU", "Hungary"],  ["IS", "Iceland"],  ["IN", "India"],  ["ID", "Indonesia"],  ["IR", "Iran, Islamic Republic of"],  ["IQ", "Iraq"],  ["IE", "Ireland"],   ["IT", "Italy"],  ["JM", "Jamaica"],  ["JP", "Japan"],  ["JO", "Jordan"],  ["KZ", "Kazakhstan"],  ["KE", "Kenya"],  ["KI", "Kiribati"],  ["KP", "Korea, Democratic People's Republic of"],  ["KR", "Korea, Republic of"],  ["KW", "Kuwait"],  ["KG", "Kyrgyzstan"],  ["LA", "Lao People's Democratic Republic"],  ["LV", "Latvia"],  ["LB", "Lebanon"],  ["LS", "Lesotho"],  ["LR", "Liberia"],  ["LY", "Libyan Arab Jamahiriya"],  ["LI", "Liechtenstein"],  ["LT", "Lithuania"],  ["LU", "Luxembourg"],  ["MO", "Macao"],  ["MK", "Macedonia, the Former Yugoslav Republic of"],  ["MG", "Madagascar"],  ["MW", "Malawi"],  ["MY", "Malaysia"],  ["MV", "Maldives"],  ["ML", "Mali"],  ["MT", "Malta"],  ["MH", "Marshall Islands"],  ["MQ", "Martinique"],  ["MR", "Mauritania"],  ["MU", "Mauritius"],  ["YT", "Mayotte"],  ["MX", "Mexico"],  ["FM", "Micronesia, Federated States of"],  ["MD", "Moldova, Republic of"],  ["MC", "Monaco"],  ["MN", "Mongolia"],  ["MS", "Montserrat"],  ["MA", "Morocco"],  ["MZ", "Mozambique"],  ["MM", "Myanmar"],  ["NA", "Namibia"],  ["NR", "Nauru"],  ["NP", "Nepal"],  ["NL", "Netherlands"],  ["AN", "Netherlands Antilles"],  ["NC", "New Caledonia"],  ["NZ", "New Zealand"],  ["NI", "Nicaragua"],  ["NE", "Niger"],  ["NG", "Nigeria"],  ["NU", "Niue"],  ["NF", "Norfolk Island"],  ["MP", "Northern Mariana Islands"],  ["NO", "Norway"],  ["OM", "Oman"],  ["PK", "Pakistan"],  ["PW", "Palau"],  ["PS", "Palestinian Territory, Occupied"],  ["PA", "Panama"],  ["PG", "Papua New Guinea"],  ["PY", "Paraguay"],  ["PE", "Peru"],  ["PH", "Philippines"],  ["PN", "Pitcairn"],  ["PL", "Poland"],  ["PT", "Portugal"],  ["PR", "Puerto Rico"],  ["QA", "Qatar"],  ["RE", "Reunion"],  ["RO", "Romania"],  ["RU", "Russian Federation"],  ["RW", "Rwanda"],  ["SH", "Saint Helena"],  ["KN", "Saint Kitts and Nevis"],  ["LC", "Saint Lucia"],  ["PM", "Saint Pierre and Miquelon"],  ["VC", "Saint Vincent and the Grenadines"],  ["WS", "Samoa"],  ["SM", "San Marino"],  ["ST", "Sao Tome and Principe"],  ["SA", "Saudi Arabia"],  ["SN", "Senegal"],  ["CS", "Serbia and Montenegro"],  ["SC", "Seychelles"],  ["SL", "Sierra Leone"],  ["SG", "Singapore"],  ["SK", "Slovakia"],  ["SI", "Slovenia"],  ["SB", "Solomon Islands"],  ["SO", "Somalia"],  ["ZA", "South Africa"],  ["GS", "South Georgia and the South Sandwich Islands"],  ["ES", "Spain"],  ["LK", "Sri Lanka"],  ["SD", "Sudan"],  ["SR", "Surititle"],  ["SJ", "Svalbard and Jan Mayen"],  ["SZ", "Swaziland"],  ["SE", "Sweden"],  ["CH", "Switzerland"],  ["SY", "Syrian Arab Republic"],  ["TW", "Taiwan, Province of China"],  ["TJ", "Tajikistan"],  ["TZ", "Tanzania, United Republic of"],  ["TH", "Thailand"],  ["TL", "Timor-Leste"],  ["TG", "Togo"],  ["TK", "Tokelau"],  ["TO", "Tonga"],  ["TT", "Trinidad and Tobago"],  ["TN", "Tunisia"],  ["TR", "Turkey"],  ["TM", "Turkmenistan"],  ["TC", "Turks and Caicos Islands"],  ["TV", "Tuvalu"],  ["UG", "Uganda"],  ["UA", "Ukraine"],  ["AE", "United Arab Emirates"],  ["GB", "United Kingdom"],  ["US", "United States"],  ["UM", "United States Minor Outlying Islands"],  ["UY", "Uruguay"],  ["UZ", "Uzbekistan"],  ["VU", "Vanuatu"],  ["VE", "Venezuela"],  ["VN", "Viet Nam"],  ["VG", "Virgin Islands, British"],  ["VI", "Virgin Islands, U.s."],  ["WF", "Wallis and Futuna"],  ["EH", "Western Sahara"],  ["YE", "Yemen"],  ["ZM", "Zambia"],  ["ZW", "Zimbabwe"],];
