
<?php

return [
    ['id' => null ,'title' => 'AED', 'value' => 'United Arab Emirates dirham',],
    ['id' => null ,'title' => 'AFN', 'value' => 'Afghan afghani',],
    ['id' => null ,'title' => 'ALL', 'value' => 'Albanian lek',],
    ['id' => null ,'title' => 'AMD', 'value' => 'Armenian dram',],
    ['id' => null ,'title' => 'ANG', 'value' => 'Netherlands Antillean guilder',],
    ['id' => null ,'title' => 'AOA', 'value' => 'Angolan kwanza',],
    ['id' => null ,'title' => 'ARS', 'value' => 'Argentine peso',],
    ['id' => null ,'title' => 'AUD', 'value' => 'Australian dollar',],
    ['id' => null ,'title' => 'AWG', 'value' => 'Aruban florin',],
    ['id' => null ,'title' => 'AZN', 'value' => 'Azerbaijani manat',],
    ['id' => null ,'title' => 'BAM', 'value' => 'Bosnia and Herzegovina convertible mark',],
    ['id' => null ,'title' => 'BBD', 'value' => 'Barbados dollar',],
    ['id' => null ,'title' => 'BDT', 'value' => 'Bangladeshi taka',],
    ['id' => null ,'title' => 'BGN', 'value' => 'Bulgarian lev',],
    ['id' => null ,'title' => 'BHD', 'value' => 'Bahraini dinar',],
    ['id' => null ,'title' => 'BIF', 'value' => 'Burundian franc',],
    ['id' => null ,'title' => 'BMD', 'value' => 'Bermudian dollar',],
    ['id' => null ,'title' => 'BND', 'value' => 'Brunei dollar',],
    ['id' => null ,'title' => 'BOB', 'value' => 'Boliviano',],
    ['id' => null ,'title' => 'BRL', 'value' => 'Brazilian real',],
    ['id' => null ,'title' => 'BSD', 'value' => 'Bahamian dollar',],
    ['id' => null ,'title' => 'BTN', 'value' => 'Bhutanese ngultrum',],
    ['id' => null ,'title' => 'BWP', 'value' => 'Botswana pula',],
    ['id' => null ,'title' => 'BYN', 'value' => 'New Belarusian ruble',],
    ['id' => null ,'title' => 'BYR', 'value' => 'Belarusian ruble',],
    ['id' => null ,'title' => 'BZD', 'value' => 'Belize dollar',],
    ['id' => null ,'title' => 'CAD', 'value' => 'Canadian dollar',],
    ['id' => null ,'title' => 'CDF', 'value' => 'Congolese franc',],
    ['id' => null ,'title' => 'CHF', 'value' => 'Swiss franc',],
    ['id' => null ,'title' => 'CLF', 'value' => 'Unidad de Fomento',],
    ['id' => null ,'title' => 'CLP', 'value' => 'Chilean peso',],
    ['id' => null ,'title' => 'CNY', 'value' => 'Renminbi|Chinese yuan',],
    ['id' => null ,'title' => 'COP', 'value' => 'Colombian peso',],
    ['id' => null ,'title' => 'CRC', 'value' => 'Costa Rican colon'],
    ['id' => null ,'title' => 'CUC', 'value' => 'Cuban convertible peso'],
    ['id' => null ,'title' => 'CUP', 'value' => 'Cuban peso',],
    ['id' => null ,'title' => 'CVE', 'value' => 'Cape Verde escudo',],
    ['id' => null ,'title' => 'CZK', 'value' => 'Czech koruna',],
    ['id' => null ,'title' => 'DJF', 'value' => 'Djiboutian franc',],
    ['id' => null ,'title' => 'DKK', 'value' => 'Danish krone',],
    ['id' => null ,'title' => 'DOP', 'value' => 'Dominican peso',],
    ['id' => null ,'title' => 'DZD', 'value' => 'Algerian dinar',],
    ['id' => null ,'title' => 'EGP', 'value' => 'Egyptian pound',],
    ['id' => null ,'title' => 'ERN', 'value' => 'Eritrean nakfa',],
    ['id' => null ,'title' => 'ETB', 'value' => 'Ethiopian birr',],
    ['id' => null ,'title' => 'EUR', 'value' => 'Euro'],
    ['id' => null ,'title' => 'FJD', 'value' => 'Fiji dollar',],
    ['id' => null ,'title' => 'FKP', 'value' => 'Falkland Islands pound',],
    ['id' => null ,'title' => 'GBP', 'value' => 'Pound sterling'],
    ['id' => null ,'title' => 'GEL', 'value' => 'Georgian lari',],
    ['id' => null ,'title' => 'GHS', 'value' => 'Ghanaian cedi',],
    ['id' => null ,'title' => 'GIP', 'value' => 'Gibraltar pound',],
    ['id' => null ,'title' => 'GMD', 'value' => 'Gambian dalasi',],
    ['id' => null ,'title' => 'GNF', 'value' => 'Guinean franc',],
    ['id' => null ,'title' => 'GTQ', 'value' => 'Guatemalan quetzal',],
    ['id' => null ,'title' => 'GYD', 'value' => 'Guyanese dollar',],
    ['id' => null ,'title' => 'HKD', 'value' => 'Hong Kong dollar',],
    ['id' => null ,'title' => 'HNL', 'value' => 'Honduran lempira',],
    ['id' => null ,'title' => 'HRK', 'value' => 'Croatian kuna',],
    ['id' => null ,'title' => 'HTG', 'value' => 'Haitian gourde',],
    ['id' => null ,'title' => 'HUF', 'value' => 'Hungarian forint',],
    ['id' => null ,'title' => 'IDR', 'value' => 'Indonesian rupiah',],
    ['id' => null ,'title' => 'INR', 'value' => 'Indian rupee'],
    ['id' => null ,'title' => 'IQD', 'value' => 'Iraqi dinar',],
    ['id' => null ,'title' => 'IRR', 'value' => 'Iranian rial',],
    ['id' => null ,'title' => 'ISK', 'value' => 'Icelandic króna',],
    ['id' => null ,'title' => 'JMD', 'value' => 'Jamaican dollar',],
    ['id' => null ,'title' => 'JOD', 'value' => 'Jordanian dinar',],
    ['id' => null ,'title' => 'JPY', 'value' => 'Japanese yen', ],
    ['id' => null ,'title' => 'KES', 'value' => 'Kenyan shilling',],
    ['id' => null ,'title' => 'KGS', 'value' => 'Kyrgyzstani som',],
    ['id' => null ,'title' => 'KHR', 'value' => 'Cambodian riel',],
    ['id' => null ,'title' => 'KMF', 'value' => 'Comoro franc',],
    ['id' => null ,'title' => 'KPW', 'value' => 'North Korean won',],
    ['id' => null ,'title' => 'KRW', 'value' => 'South Korean won'],
    ['id' => null ,'title' => 'KWD', 'value' => 'Kuwaiti dinar',], ['id' => null ,'title' => 'KYD', 'value' => 'Cayman Islands dollar',],
    ['id' => null ,'title' => 'KZT', 'value' => 'Kazakhstani tenge',],
    ['id' => null ,'title' => 'LAK', 'value' => 'Lao kip',], ['id' => null ,'title' => 'LBP', 'value' => 'Lebanese pound',],
    ['id' => null ,'title' => 'LKR', 'value' => 'Sri Lankan rupee',],
    ['id' => null ,'title' => 'LRD', 'value' => 'Liberian dollar',], ['id' => null ,'title' => 'LSL', 'value' => 'Lesotho loti',],
    ['id' => null ,'title' => 'LYD', 'value' => 'Libyan dinar',],
    ['id' => null ,'title' => 'MAD', 'value' => 'Moroccan dirham',],
    ['id' => null ,'title' => 'MDL', 'value' => 'Moldovan leu',],
    ['id' => null ,'title' => 'MGA', 'value' => 'Malagasy ariary',],
    ['id' => null ,'title' => 'MKD', 'value' => 'Macedonian denar',],
    ['id' => null ,'title' => 'MMK', 'value' => 'Myanmar kyat',],
    ['id' => null ,'title' => 'MNT', 'value' => 'Mongolian tögrög',],
    ['id' => null ,'title' => 'MOP', 'value' => 'Macanese pataca',],
    ['id' => null ,'title' => 'MRO', 'value' => 'Mauritanian ouguiya',],
    ['id' => null ,'title' => 'MUR', 'value' => 'Mauritian rupee',],
    ['id' => null ,'title' => 'MVR', 'value' => 'Maldivian rufiyaa',], ['id' => null ,'title' => 'MWK', 'value' => 'Malawian kwacha',],
    ['id' => null ,'title' => 'MXN', 'value' => 'Mexican peso',],
    ['id' => null ,'title' => 'MXV', 'value' => 'Mexican Unidad de Inversion',],
    ['id' => null ,'title' => 'MYR', 'value' => 'Malaysian ringgit',],
    ['id' => null ,'title' => 'MZN', 'value' => 'Mozambican metical',],
    ['id' => null ,'title' => 'NAD', 'value' => 'Namibian dollar'],
    ['id' => null ,'title' => 'NGN', 'value' => 'Nigerian naira' ],
    ['id' => null ,'title' => 'NIO', 'value' => 'Nicaraguan córdoba',],
    ['id' => null ,'title' => 'NOK', 'value' => 'Norwegian krone',],
    ['id' => null ,'title' => 'NPR', 'value' => 'Nepalese rupee',],
    ['id' => null ,'title' => 'NZD', 'value' => 'New Zealand dollar',],
    ['id' => null ,'title' => 'OMR', 'value' => 'Omani rial',],
    ['id' => null ,'title' => 'PAB', 'value' => 'Panamanian balboa',],
    ['id' => null ,'title' => 'PEN', 'value' => 'Peruvian Sol',],
    ['id' => null ,'title' => 'PGK', 'value' => 'Papua New Guinean kina',],
    ['id' => null ,'title' => 'PHP', 'value' => 'Philippine peso' ],
    ['id' => null ,'title' => 'PKR', 'value' => 'Pakistani rupee'],
    ['id' => null ,'title' => 'PLN', 'value' => 'Polish złoty'],
    ['id' => null ,'title' => 'PYG', 'value' => 'Paraguayan guaraní'],
    ['id' => null ,'title' => 'QAR', 'value' => 'Qatari riyal',],
    ['id' => null ,'title' => 'RON', 'value' => 'Romanian leu',],
    ['id' => null ,'title' => 'RSD', 'value' => 'Serbian dinar',],
    ['id' => null ,'title' => 'RUB', 'value' => 'Russian ruble',],
    ['id' => null ,'title' => 'RWF', 'value' => 'Rwandan franc',],
    ['id' => null ,'title' => 'SAR', 'value' => 'Saudi riyal',],
    ['id' => null ,'title' => 'SBD', 'value' => 'Solomon Islands dollar',],
    ['id' => null ,'title' => 'SCR', 'value' => 'Seychelles rupee',],
    ['id' => null ,'title' => 'SDG', 'value' => 'Sudanese pound',],
    ['id' => null ,'title' => 'SEK', 'value' => 'Swedish krona',],
    ['id' => null ,'title' => 'SGD', 'value' => 'Singapore dollar',],
    ['id' => null ,'title' => 'SHP', 'value' => 'Saint Helena pound',],
    ['id' => null ,'title' => 'SLL', 'value' => 'Sierra Leonean leone',],
    ['id' => null ,'title' => 'SOS', 'value' => 'Somali shilling',],
    ['id' => null ,'title' => 'SRD', 'value' => 'Surivaluese dollar',],
    ['id' => null ,'title' => 'SSP', 'value' => 'South Sudanese pound',],
    ['id' => null ,'title' => 'STD', 'value' => 'São Tomé and Príncipe dobra',],
    ['id' => null ,'title' => 'SVC', 'value' => 'Salvadoran colón',],
    ['id' => null ,'title' => 'SYP', 'value' => 'Syrian pound',],
    ['id' => null ,'title' => 'SZL', 'value' => 'Swazi lilangeni',],
    ['id' => null ,'title' => 'THB', 'value' => 'Thai baht'],
    ['id' => null ,'title' => 'TJS', 'value' => 'Tajikistani somoni',],
    ['id' => null ,'title' => 'TMT', 'value' => 'Turkmenistani manat',],
    ['id' => null ,'title' => 'TND', 'value' => 'Tunisian dinar',],
    ['id' => null ,'title' => 'TOP', 'value' => 'Tongan paʻanga',],
    ['id' => null ,'title' => 'TRY', 'value' => 'Turkish lira',],
    ['id' => null ,'title' => 'TTD', 'value' => 'Trinidad and Tobago dollar',],
    ['id' => null ,'title' => 'TWD', 'value' => 'New Taiwan dollar',],
    ['id' => null ,'title' => 'TZS', 'value' => 'Tanzanian shilling',],
    ['id' => null ,'title' => 'UAH', 'value' => 'Ukrainian hryvnia'],
    ['id' => null ,'title' => 'UGX', 'value' => 'Ugandan shilling',],
    ['id' => null ,'title' => 'USD', 'value' => 'United States dollar'],
    ['id' => null ,'title' => 'UYI', 'value' => 'Uruguay Peso en Unidades Indexadas',],
    ['id' => null ,'title' => 'UYU', 'value' => 'Uruguayan peso',],
    ['id' => null ,'title' => 'UZS', 'value' => 'Uzbekistan som',],
    ['id' => null ,'title' => 'VEF', 'value' => 'Venezuelan bolívar',],
    ['id' => null ,'title' => 'VND', 'value' => 'Vietvaluese đồng'],
    ['id' => null ,'title' => 'VUV', 'value' => 'Vanuatu vatu',],
    ['id' => null ,'title' => 'WST', 'value' => 'Samoan tala',],
    ['id' => null ,'title' => 'XAF', 'value' => 'Central African CFA franc',],
    ['id' => null ,'title' => 'XCD', 'value' => 'East Caribbean dollar',],
    ['id' => null ,'title' => 'XOF', 'value' => 'West African CFA franc',],
    ['id' => null ,'title' => 'XPF', 'value' => 'CFP franc',],
    ['id' => null ,'title' => 'XXX', 'value' => 'No currency',],
    ['id' => null ,'title' => 'YER', 'value' => 'Yemeni rial',],
    ['id' => null ,'title' => 'ZAR', 'value' => 'South African rand',],
    ['id' => null ,'title' => 'ZMW', 'value' => 'Zambian kwacha',],
    ['id' => null ,'title' => 'ZWL', 'value' => 'Zimbabwean dollar',]
];
